<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageVersion Include="lcmsNET" Version="1.2.1" />
    <PackageVersion Include="MSTest" Version="4.3.2" />
  </ItemGroup>
</Project>
