<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICCProfileViewer.Core\ICCProfileViewer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="lcmsNET" />
  </ItemGroup>

</Project>
